### ISSUE TITLE
Make both images (GMaps + image) the same size and right next to each other.

### ISSUE THREAD

**Issue by ShivanKaul** [ShivanKaul/Expendr#15]

**Comment by draringi** [comment]
Ideally, this will be true for desktop, while phone will show them one on top the other (given the reduced screen space)

**Comment by ShivanKaul** [comment]
Yes, but we don't need to bother about phone right now for the purposes of the demo. It's true though that while demoing screen size can get messed up, and we should take care of this if possible.
